export { default as Home } from './Home'
export { default as Privacy } from './Privacy'
export { default as Terms } from './Terms'
export { default as FAQS } from './Faqs'
export { default as Contact } from './Contact'
export { default as About } from './About'
export { default as Career } from './Career'
export { default as Services } from './Services'